#!/bin/bash
# assuming SAMcov was run for SAM(g2)
# run as DoEpiICA <patient ID> <file prefix>
SAMwts -r $1 -d $2_c,rfhp1.0Hz,ee -c Global,20-70Hz -C -Z -x "-10 10" -y "-9 9" -z "0 14" -s 0.5 -v
cp ~/SAM_BIU/matlab/epilepsy/ICA $1/SAM/ICA
SAMspm -r $1 -d $2_c,rfhp1.0Hz,ee -a Global,0-100Hz,Global,ECD -c Global,0-100Hz,Global,ECD -m ICA -D 1 -P -v
cp $1/SAM/ICA,* $1/$2_ICAspm.svl
SAMerf -r $1 -d $2_c,rfhp1.0Hz,ee -w Global,0-100Hz,Global,ECD -m 1 -f "3 70" -v -t "-0.025 0.025" -b "-0.2 -0.15" -z 3
cp $1/SAM/Global,0-100Hz,Global,ECD,Trig-1,-25-25ms,3-70Hz,ERP.svl $1/$2_ICAerf.svl
